version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = [
    "nodejs",
    "jquery",
    "browser",
    "mongo"
  ]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "php"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "dotnet-format"